spring.application.name=Access Governance Manager

spring.datasource.url=jdbc:mysql://mysql:3306/access_governance_manager
spring.datasource.username=root
spring.datasource.password=Prethi@12

spring.cache.type=simple
spring.data.redis.host=redis
spring.data.redis.port=6379